feat(gdb: Multithreading (part 2)
This is a combination of 30 commits.

nit(gdb): remove single gdb restriction
feat(gdb): set affinity in threads, fetch vcpu id from object
nit(gdb): Improve cpu_affinity handling
nit(gdb): have swap use AcqRel ordering

fix(gdb): GDB truncates thread-ids supplied by us, so truncate them before supplying them to GDB to ensure consistency

```
[TRACE uhyvelib::linux::gdb] tid2vcpu = {140098616854208: 0}
[TRACE uhyvelib::linux] Active thread: 140098616854208
[TRACE uhyvelib::linux::gdb] tid_to_vcpuw(1078625984)

thread 'main' (4706) panicked at src/linux/gdb/mod.rs:237:37:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
>>> 140098616854208 & 1078625984
1078625984
>>> 140098616854208 ^ 1078625984
140097538228224
>>> x = 140098616854208 ^ 1078625984
>>> f"{x:#x}"
'0x7f6b00000000'
```

fix(gdb): Fix most cases of GDB not being able to interrupt the target

These were actually multiple issues in a trenchcoat:
- set_scheduler_lock is called very late (often just before resume)
- for cleanliness, we now always check if we're stopped (per vcpu), even on first iteration
- wait in the vcpu threads for the gdb connection to be fully initialized,
  to ensure that the breakpoints are set correctly (`full_init_event`)

It appears that this leads to a breakpoint getting hit in _start,
but at least it otherwise appears to work perfectly almost always.
Remaining failures are probably due to the non-intended treatment of `full_init_event`
(it should've been paired with an `AtomicBool` to ensure spurious wakeups don't lead to protocol errors).

fix(gdb): Truncate TIDs to be provided to GDB to 31 bits

See also:
- https://github.com/daniel5151/gdbstub/issues/193
- https://sourceware.org/bugzilla/show_bug.cgi?id=33979

nit(gdb): Rename 'struct Freewheel' to 'struct GdbVcpuManager'
nit(gdb): Rename 'fn backend_report_invalid_value' to 'fn backend_invalid_value'
nit(gdb): Rename Tid resolvers
nit(gdb): Fix VcpuWrapper::tid comment
nit(gdb): Rename 'ResumeMode::Freewheel' to 'ResumeMode::FreeWheeling'
nit(gdb/resume): renamse '.free_wheel' to '.r#continue'
nit(gdb): Rename '.finished_initializing' to '.set_finished_initializing'
chore(gdb): Mark GdbVcpuManager getters as non-pub

Co-authored-by: Panagiotis "Ivory" Vasilopoulos <git@n0toose.net>