deps: rand shouldn't be optional
reason:
```
error[E0432]: unresolved import `rand`
 --> src/arch/x86_64/mod.rs:6:5
  |
6 | use rand::Rng;
  |     ^^^^ help: a similar path exists: `vmm_sys_util::rand`

error[E0433]: failed to resolve: use of unresolved module or unlinked crate `rand`
  --> src/arch/x86_64/mod.rs:20:16
   |
20 |     let mut rng = rand::rng();
   |                   ^^^^ use of unresolved module or unlinked crate `rand`
   |
   = help: if you wanted to use a crate named `rand`, use `cargo add rand` to add it to your `Cargo.toml`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `uhyve` (lib) due to 2 previous errors
```

This also fixes a few other nitpicks in Cargo.toml,
in particular, it removes the `aslr` feature, which has no effect anymore.