fix(bin/uhyve): fix panic when affinity doesn't match with cpu_count
The bug was introduced since 0384c1d050057035d892e2b52f825a4be4bc73a7.

Error message, originally:
------
fogti@qrink2 uhyve % RUST_BACKTRACE=1 cargo run -- data/x86_64/hello_c --affinity 1,2,3
   Compiling uhyve v0.0.29 (/import/y2data/home/fogti/devel/uhyve)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.89s
     Running `target/debug/uhyve data/x86_64/hello_c --affinity 1,2,3`

thread 'main' panicked at src/bin/uhyve.rs:312:22:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/panicking.rs:145:5
   3: core::option::unwrap_failed
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/option.rs:2072:5
   4: core::option::Option<T>::unwrap
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1005:21
   5: uhyve::CpuArgs::get_affinity::{{closure}}
             at ./src/bin/uhyve.rs:312:7
   6: core::option::Option<T>::map
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1146:29
   7: uhyve::CpuArgs::get_affinity
             at ./src/bin/uhyve.rs:305:17
   8: uhyve::run_uhyve
             at ./src/bin/uhyve.rs:380:26
   9: uhyve::main
             at ./src/bin/uhyve.rs:405:16
  10: core::ops::function::FnOnce::call_once
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
------

Error message after simple fix (making sure the requested ids actually match those assigned by clap):
------
fogti@qrink2 uhyve % RUST_BACKTRACE=1 cargo run -- data/x86_64/hello_c --affinity 1,2,3
   Compiling uhyve v0.5.0 (/import/y2data/home/fogti/devel/uhyve)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.82s
     Running `target/debug/uhyve data/x86_64/hello_c --affinity 1,2,3`

thread 'main' panicked at /import/y2data/home/fogti/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.42/src/builder/arg.rs:4275:29:
Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_display
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/panicking.rs:268:5
   3: core::option::expect_failed
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/option.rs:2081:5
   4: core::option::Option<T>::expect
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:960:21
   5: clap_builder::builder::arg::Arg::get_min_vals
             at /import/y2data/home/fogti/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.42/src/builder/arg.rs:4275:29
   6: clap_builder::builder::arg::Arg::stylize_arg_suffix
             at /import/y2data/home/fogti/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.42/src/builder/arg.rs:4602:40
   7: clap_builder::builder::arg::Arg::stylized
             at /import/y2data/home/fogti/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.42/src/builder/arg.rs:4590:34
   8: <clap_builder::builder::arg::Arg as core::fmt::Display>::fmt
             at /import/y2data/home/fogti/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.42/src/builder/arg.rs:4710:14
   9: <&T as core::fmt::Display>::fmt
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2655:62
  10: core::fmt::rt::Argument::fmt
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/fmt/rt.rs:173:76
  11: core::fmt::write
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/fmt/mod.rs:1465:25
  12: <&mut W as core::fmt::Write::write_fmt::SpecWriteFmt>::spec_write_fmt
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/fmt/mod.rs:229:21
  13: core::fmt::Write::write_fmt
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/core/src/fmt/mod.rs:234:14
  14: alloc::fmt::format::format_inner
             at /rustc/4229c2e708ce796c71747b7fa177ff4ef9aa794c/library/alloc/src/fmt.rs:649:14
  15: alloc::fmt::format::{{closure}}
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/fmt.rs:654:34
  16: core::option::Option<T>::map_or_else
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1252:21
  17: alloc::fmt::format
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/fmt.rs:654:19
  18: uhyve::CpuArgs::get_affinity::{{closure}}
             at ./src/bin/uhyve.rs:219:19
  19: core::option::Option<T>::map
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1146:29
  20: uhyve::CpuArgs::get_affinity
             at ./src/bin/uhyve.rs:210:17
  21: uhyve::run_uhyve
             at ./src/bin/uhyve.rs:480:34
  22: uhyve::main
             at ./src/bin/uhyve.rs:494:16
  23: core::ops::function::FnOnce::call_once
             at /import/y2data/home/fogti/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
------